# =========================================================================
# CONFIGURATION SONARQUBE POUR LE PROJET CABINET MÉDICAL ODOO 17
# =========================================================================

# Identification du projet dans SonarQube
sonar.projectKey=cabinet-medical-odoo17
sonar.projectName=Cabinet Medical Odoo 17
sonar.projectVersion=17.0.1.0.2

# Répertoire source du code à analyser
sonar.sources=custom_addons/cabinet_medical

# Répertoire des tests unitaires
sonar.tests=custom_addons/cabinet_medical/tests

# Encodage des fichiers sources
sonar.sourceEncoding=UTF-8

# Fichiers et extensions inclus (Python backend et XML views/business logic)
sonar.inclusions=**/*.py,**/*.xml
sonar.javascript.exclusions=**/*
sonar.typescript.exclusions=**/*

# Exclusions (fichiers générés, caches, ontologies brutes volumineuses)
sonar.exclusions=**/tests/**,**/static/lib/**,**/__pycache__/**,custom_addons/cabinet_medical/data/**,custom_addons/cabinet_medical/controllers/**

# Exclusions pour la couverture de test (les modèles IA et les data brutes)
sonar.coverage.exclusions=custom_addons/cabinet_medical/models/ml_no_show.joblib,custom_addons/cabinet_medical/data/**,custom_addons/cabinet_medical/controllers/**

# Chemin vers le rapport de couverture
sonar.python.coverage.reportPaths=coverage.xml
