{
    'name': 'Cabinet Médical',
    'version': '17.0.1.0.7',
    'summary': 'Gestion d un cabinet médical',
    'author': 'Ton Nom',
    'category': 'Healthcare',
    'license': 'LGPL-3',
    'depends': ['base', 'mail', 'web', 'auth_signup', 'portal'],
    'data': [
        'security/security.xml',
        'security/portal_security.xml',
        'security/ir.model.access.csv',
        'data/appointment_sequence.xml',
        'data/facture_sequence.xml',
        'data/bordereau_sequence.xml',
        'data/assurance_data.xml',
        'data/portal_invite_template.xml',
        'data/mail_templates.xml',
        'data/cron_data.xml',
        'data/demo_users.xml',

        'reports/ordonnance_report.xml',
        'reports/facture_template.xml',
        'reports/recu_template.xml',
        'reports/bs1_template.xml',
        'reports/feuille_soins_template.xml',
        'reports/bordereau_report.xml',
        'reports/bulletin_soins_report.xml',

       'views/menu_root.xml',
        'views/wizard_import_patients_view.xml',
        'views/patient_views.xml',
        'views/consultation_views.xml',
        'views/rendezvous.xml',
        'views/rendezvous_secretaire.xml',
        'views/rendezvous_medecin.xml',
        'views/assurance_views.xml',
        'views/res_config_settings_view.xml',
        'views/prescription_views.xml',
        'views/wizard_creer_patient_view.xml',
        'views/wizard_suivi.xml',
        'views/wizard_signer_ordonnance_views.xml',
        'views/doctor_profile_views.xml',
        'views/acte_parametrage_views.xml',

        'views/dashboard_views.xml',
        'views/bordereau_views.xml',
        'views/facturation_views.xml',
        'views/menu.xml',
        'views/login_templates.xml',
        'views/portal_templates.xml',
        'views/hide_waffle_view.xml',
        'views/reset_password_email_view.xml',
    ],
    'demo': [],
    'qweb': [
        'static/src/xml/*.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'cabinet_medical/static/src/css/medical_styles.css',
            'cabinet_medical/static/src/css/hide_gear.css',
            'cabinet_medical/static/src/css/rdv_dashboard.css',
            'cabinet_medical/static/src/css/hide_apps_menu.css',
            'cabinet_medical/static/src/css/hide_popup_buttons.css',
            'cabinet_medical/static/src/js/rdv_filter_buttons_v2.js',
            'cabinet_medical/static/src/js/professional_ui.js',
            'cabinet_medical/static/src/js/ai_dashboard.js',
            'cabinet_medical/static/src/js/cnam_dashboard.js',
            'cabinet_medical/static/src/js/hide_app_switcher.js',
            'cabinet_medical/static/src/js/live_search.js',
            'cabinet_medical/static/src/js/user_menu_cleanup.js',
            'cabinet_medical/static/src/xml/rdv_filter_buttons.xml',
            'cabinet_medical/static/src/xml/ai_dashboard.xml',
            'cabinet_medical/static/src/xml/cnam_dashboard.xml',
        ],
        'web.assets_frontend': [
            'cabinet_medical/static/src/css/medical_styles.css',
        ],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
}