from . import patient
from . import consultation
from . import acte
from . import prescription
from . import assurance
from . import rendezvous
from . import res_config_settings
from . import facture
from . import wizard_creer_patient
from . import wizard_import_patients
from . import wizard_suivi
from . import bordereau
from . import acte_parametrage
from . import res_company
from . import dashboard_ai
from . import ir_http
from . import notification
from . import ir_mail_server
from . import ml_no_show
from . import res_users
from . import wizard_signer_ordonnance
from . import wizard_doctor_profile