services:
  # =========================================================================
  # 1. APPLICATION MÉDICALE : BASE DE DONNÉES POSTGRESQL 15
  # =========================================================================
  db:
    image: postgres:15
    container_name: cabinet_db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo_secret_pwd
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    restart: unless-stopped

  # =========================================================================
  # 2. APPLICATION MÉDICALE : SERVEUR ODOO 17 (AVEC MODULE CABINET_MEDICAL)
  # =========================================================================
  odoo:
    image: cabinet-medical-odoo:latest
    container_name: cabinet_odoo
    depends_on:
      - db
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo_secret_pwd
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - /vagrant/custom_addons:/mnt/extra-addons
      - ./odoo.conf:/etc/odoo/odoo.conf
    restart: unless-stopped

volumes:
  odoo-db-data:
  odoo-web-data: